defaults:
  - base_target_llm
  - _self_

llm_params:
  model_name: "CodeLlama-7b-Python-hf"
  checkpoint: 'meta-llama/CodeLlama-7b-Python-hf' # or replace with local DIR
prompt_manager:
  prompt_template:
    - key: system_message
      msg: "<s>[INST]"
    - key: full_instruct
      msg: "{full_instruct}"  # loaded from context
    - key: separator
      msg: "[/INST]"
    - key: target
      msg: "{target}"  # loaded from context